services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    hostname: "${POSTGRES_HOST}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    hostname: "${REDIS_HOST}"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    networks:
      - shared

  bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - shared

volumes:
  postgres_data:
  redis_data:

networks:
  shared:
    name: global_shared