services:
  bot:
    build:
      context: .
    container_name: ukrduzt_v2_bot
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5432:5432"

volumes:
  postgres_data:
