"""add site settings

Revision ID: efa798fa2d38
Revises: be688a049551
Create Date: 2025-02-12 10:17:09.285935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa798fa2d38'
down_revision: Union[str, None] = 'be688a049551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, default=81),
    sa.Column('semester', sa.Integer(), nullable=False, default=2),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_settings')
    # ### end Alembic commands ###
