"""baseline

Revision ID: 3bbd7eeef9c7
Revises: 
Create Date: 2025-02-07 16:14:52.922658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbd7eeef9c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=True),
    sa.Column('user_faculty', sa.Integer(), nullable=True),
    sa.Column('user_course', sa.Integer(), nullable=True),
    sa.Column('user_group', sa.Integer(), nullable=True),
    sa.Column('user_group_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='unique_user_id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='unique_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
